name: Clima diario a Telegram

on:
  schedule:
    - cron: "0 11 * * *" # 6:00 AM Perú (11:00 UTC)
    - cron: "0 18 * * *" # 1:00 PM Perú (18:00 UTC)
  workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
  enviar_clima:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          pip install requests beautifulsoup4

      - name: Ejecutar script de clima
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          python senamhi_telegram.py
